version: "3.8"

services:
  api:
    build: ./Api
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Initial Catalog=SPAv2_master;User Id=QPRocky;Password=Manager79;TrustServerCertificate=true;
      - ASPNETCORE_ENVIRONMENT=Development
      - ACCEPT_EULA=Y

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
