import { AxiosError } from 'axios';

const getAxiosError = (err: unknown) => {
  const axiosError = err as AxiosError;

  // ApiResponseException with message
  if ((axiosError.response?.data as string) !== '') {
    return axiosError.response?.data as string;
  }

  // ApiResponseException without message. Shows raw error message generated by net Core
  if (axiosError.message) return axiosError.message;

  return 'Jotain meni pieleen';
};

export default getAxiosError;
